name: Export and Deploy Godot Project to Github Pages

on:
  push:
    branches:
      - main  # Change this if needed

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: Rockstar # Change this to your game's name
  PROJECT_PATH: godot_project/  # Set to "." if your `project.godot` is in the root directory
  EXPORT_DIR: .

jobs:
  export:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: "$EXPORT_DIR/web/" # The folder the action should deploy.
